version: 0.1

environment_variables:
  plaintext:
    NODE_ENV: "development"

phases:
  install:
    commands:
      - echo Nothing to do in install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - NODE_ENV=production npm install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  discard-paths: no
